### ISSUE TITLE
define 2nd-order syntax & its model theory

### ISSUE THREAD

**Issue by jonsterling** [jonsterling/aspects-of-cubical-type-theory#3]
there's a couple styles of semantics that we might try:

1. fiore style: substitution monoidal structure, signature endofunctor, algebras, etc.
2. lawvere style: define the syntax, derive the classifying category from this, then define models as some kind of (finite-product-preserving) functor into `SET` or other base category.

Now, I've done (1) before and it works fine; curious whether there is any argument for doing something along the lines of (2) though. It seems much easier at least in the first-order case... @freebroccolo do you have any thoughts on this question?

**Comment by freebroccolo** [comment]
@jonsterling 

So there are a ton of different ways of talking about models or algebras for theories as free structures over signatures. Most of the ones I've looked at have some story about how to derive the one from the other. Sometimes they are actually equivalent but usually it is not quite the case.

I think *almost* all of them (all of them?) have a translation to some variant of monads (more later).

For (1), the Fiore style can be understood in terms of relative monads. Relative monads can in term be understood in terms of skew monoids in skew monoidal categories (multiplicative style) or similarly in terms of equivalent extension systems. Uustalu explains the relative monads in terms of skew monoidal categories somewhere and I think Curien used the extension style somewhere. I don't recall the exact references though.

For (2), Voevodsky [recently explained](http://arxiv.org/pdf/1601.02158v1.pdf) Lawvere theories in terms of relative monads. There are probably other references.

I'm not sure I have a strong preference between the two. I don't think I've ever used colored Lawvere theories directly (*which I think can be understood as [PROPs](https://ncatlab.org/nlab/show/PROP) with extra structure maps for the cartesian case*) but I *have* used operads a bunch and algebras for an operad are similar.

An algebra for an operad `O` is an operad morphism `alg : O -> Endo(Set)` where `Endo(S)` is the endomorphism operad on a monoidal category `S`. Since the operad structure is preserved, this is obviously "product preserving" in the appropriate sense. Operads can, like monads, be defined as monoids in a monoidal category: in this case [monoids](https://ncatlab.org/nlab/show/operad#DefinitionAsMonoid) in the monoidal category of presheafs over (colored) [sequences](https://ncatlab.org/nlab/show/colored+symmetric+sequence).

Some examples:

* [`Endo`](https://github.com/freebroccolo/agda-cube-category/blob/master/src/Cube/Operad.agda) operad for the monoidal cube category
* [`Endo`](https://github.com/freebroccolo/agda-properads/blob/master/src/Main.agda#L258) properad on `SET` (with sample maps [here](https://github.com/freebroccolo/agda-properads/blob/master/src/Main.agda#L344))
* [Monoids](https://github.com/freebroccolo/agda-dendroidal-sets/blob/master/src/Operad.agda#L119-L138) as operad algebras (with `⟨ℕ, +⟩` as an example)

Note that the category of *forests* for a *planar* operad (the structure used to type non-biased operad composition or multicomposition) is in fact at least a [colored `PRO`](https://github.com/freebroccolo/agda-operads/blob/master/src/Operads/Operad/Planar.agda#L36), i.e., a `PROP` without the permutation maps. If you use symmetric operads it is a `PROP`.

From my perspective, working with Operads (which are just multicategories) is probably better than Lawvere theories. You have the `PRO(P)` structure but you also get multicomposition, etc. Operad multicomposition is a generalized version of cut for the sequence calculus. You can easily derive the familiar biased or [*placed* version of cut](https://github.com/freebroccolo/agda-operads/blob/master/src/Operads/Operad/Planar.agda#L385-L392) using the `PRO(P)` structure on the forests. So maybe you could argue that using operads gives you a nicer proof theory.

There's much more literature on operads too, though to be fair most of it is not about colored operads or about applications to universal algebra directly. More of it seems to be about homotopy theory. Very recently there is some work on homotopy theory for colored PROPs too though.

Back to the bit about monads, there is a paper from Hyland and co [here](https://www.irif.univ-paris-diderot.fr/~mellies/mpri/mpri-ens/articles/hyland-power-lawvere-theories-and-monads.pdf) which talks more about the relationship between Lawvere theories and monads. I haven't read it but I think it's more of a conceptual overview than a technical one like the Voevodsky paper.

Probably the "holy grail" of unifying many of these approaches, so far at least, is the recent work from Berger, Melliès, and Weber on [monads-with-arities](http://www.sciencedirect.com/science/article/pii/S0022404912000874). It's been awhile since I looked at it but IIRC, they describe a certain situation where one has a generalized monad over a structure of arities which is suitably nerve-like (i.e., can be traversed and local structure manipulated with the face/degeneracy maps). Weber has since done a ton of interesting work on stuff related to monads with arities (e.g., multitensors). Recent work from Kock on hypergraphs and properads from polynomials is also related but I'd have to go back and read the paper to say more about it.

Regarding the monads-with-arities paper, one of the examples they give is globular operads, where the arities are "globular cardinals". You can think of globular cardinals as "degenerated pasting diagrams" in the exact same way that natural numbers are "degenerated" lists (of unit). In this case you replace unit in the nat/list case with the terminal globular set (or use a non-terminal globular set in the fully colored, non-degenrated case).

I haven't really thought about it but this monad-with-arities approach would probably be by far the nicest way to give an abstract account of cubical syntax.

**Comment by jonsterling** [comment]
@freebroccolo thanks for this fantastic comment! I'll think about this a bit and follow the trail of your links...

**Comment by freebroccolo** [comment]
So to be a bit more explicit about how you might use operads here as an alternative to (2), you could start by taking the [Free operad](https://github.com/freebroccolo/agda-operads/blob/master/src/Operads/Operad/Planar/Free.agda) over a signature `Ψ ` viewed as an [operad collection](https://github.com/freebroccolo/agda-operads/blob/master/src/Operads/Operad/Planar/Collection.agda) (hypergraph) and then define a map `alg : Free(Ψ) -> Endo(SET)`.

**Comment by freebroccolo** [comment]
Regarding globular cardinals from the monads-with-arities reference, here are some more links :)

* [globular cardinals](https://github.com/freebroccolo/agda-nerve/blob/master/src/Main.agda#L215-L225) (called `Shape`) with [example](https://github.com/freebroccolo/agda-nerve/blob/master/src/Main.agda#L282-L283)
* [globular pasting diagrams](https://github.com/freebroccolo/agda-nerve/blob/master/src/Main.agda#L215-L225) with [example](https://github.com/freebroccolo/agda-nerve/blob/master/src/Main.agda#L285-L298)

IIRC, globular pasting diagrams are objects of Joyal's category `Θ` where *cellular sets* are defined as presheafs on `Θ`. I think the reference has more details. I don't define all of the maps in the above links but as you can already see it has a sort of nerve-like flavor: instead of the standard simplicial nerve as linear paths, you have free paths in multiple dimensions from the underlying globular sets.

So a globular operad gives you a notion of a *globular theory* where the arities associated to the operators are cardinals or pasting diagrams depending on whether you want a colored version or not. A standard example from type theory would be given by the identity type. Composition for this globular operad would paste all paths in the diagram together, respecting dimension.

You should be able to do something similar for cubes but I'm not quite sure what it would look like.

**Comment by freebroccolo** [comment]
Also see this really excellent [blog post](https://golem.ph.utexas.edu/category/2009/10/generalized_operads_in_classic.html) relevant to all of this by Mike Shulman on the n-category café. He describes the exact relationship between some of the structures I mentioned with respect to functorial semantics.

**Comment by jonsterling** [comment]
@freebroccolo This all seems very interesting... I am curious to learn more about the use of operads in this stuff, so I'll read Mike's post.

In the meanwhile, I'm thinking of doing functorial semantics in the style that Fiore & Mahmoud showed to be equivalent to the usual (essentially monadic) model theory, since the functorial semantics are fairly quick to write down and easy (I think) to understand. I guess the thing is to rig up just the right notion of classifying category.

**Comment by jonsterling** [comment]
@freebroccolo Actually, re: my above comment, things may be a bit more complicated than I was initially thinking. So I may keep learning a bit before committing to a style of model theory.

**Comment by freebroccolo** [comment]
Yeah, there's a lot to consider given all the different possibilities.

I think the operad approach is quite elegant but it still may not be the right choice here. The main issue is that with operads (or Lawvere theories) you'll need to provide the story for binding because the usual free operad won't give you this alone. I don't expect the issue is particularly difficult to address but I haven't worked out all of the details directly with operads before either so it may be more difficult than I think.

**Comment by freebroccolo** [comment]
Regarding my last comment, I guess the "obvious" thing to do would be to work with free closed operads instead and define the algebras with respect to `Endo` for closed monoidal categories. Maybe I'll have a go at seeing what that looks like…

**Comment by jonsterling** [comment]
@freebroccolo Hmm, I was reading a bit deeper in that Fiore-Mahmoud stuff just now and I think (again, I know I'm oscillating) it may be fairly simple to try the functorial style. See http://www.cl.cam.ac.uk/~mpf23/papers/Types/soat.pdf and the paragraph labeled "The theory of a presentation"...

In this paper, they seem to rig things up in the following way:

1. In "Theory of equality", they define a category `M` which is like the classifying category for the empty (2nd-order) signature.

2. They define the notion of a "second order algebraic theory" as a strict cartesian functor `M -> T` that preserves some stuff (with `T` some  cartesian category); a functorial semantics for this theory is a cartesian functor `T -> Set`.

3. Next, for an equational presentation of a 2nd-order signature `<Σ,E>`, they define a category `M[E]` which is the classifying category for this equational presentation.

4. There is a canonical functor `M -> M[E]`, so together all the above stuff qualifies as a "second-order algebraic theory".

Now, all the above work seems to be devoted toward showing that the functorial models and the algebra semantics are the same basic thing. Since it's already been proved, all we need in this case is the insight that for a second-order signature `Σ`, we can define the classifying category `Cl[Σ]` (which will be just like `M[E]` in Fiore/Mahmoud, but without the equivalence classes, since we're just doing a pure theory). Then, models of `Σ` are precisely the cartesian functors `Cl[Σ] -> Set`. So, I think that this could end up being a fairly simple way of doing things, given that Fiore et al have done all the legwork beforehand.

I'm still quite interested in the operads stuff, but I'm wondering if you have any remark on my comment above.

**Comment by freebroccolo** [comment]
I'll have to take another look at it since I don't remember most of the details but everything you just said sounds pretty reasonable to me. The whole operad thing is kind of a yak shave to be honest and is probably more interesting only if the point is really to start working out a framework for higher dimensional stuff straight away.

Regarding my previous comment, something I just realized is that you can probably avoid needing the extra structure for something like a closed operad after all if you change the underlying monad from lists to rose trees. Actually you don't quite want rose trees but bouquets (lists of rose trees, or the head of a rose tree fork) which is probably still a monad.

This is in fact closer to an approach I've been working on elsewhere. It should give you arities of a higher-order directly in the operad structure. To take advantage of that, you'd change the usual free operad to have an extra constructor for variables. The intention is that these would behave like projections in a model. It's slightly more complicated than that in practice because the operators can have an arity of nth-order, so the projections are more like a cut operation wrt to the context unless what you are projecting already has an empty context at the fork.

**Comment by freebroccolo** [comment]
So I just looked through that paper again and I think following their approach is probably the best bet. There's a lot of interesting stuff you could consider with one of these alternative approaches but it will mean having to work out a lot of low level stuff that you could just avoid following Fiore.

**Comment by jonsterling** [comment]
@freebroccolo Ok, thanks very much for having a look! I think I only understood just today what was going on in some of that Fiore stuff which I hadn't needed last time around, heh...
